------------------------------------------------------------------------------------ Variables ----------------------------------------------------------------------------------

[Variables]
ChangelogLink1="https://github.com/NoahBRostant/Roundify/releases/download/v0.10.0/Roundify_0.10.0.rmskin"
ChangelogLink2="https://github.com/NoahBRostant/Roundify/releases/download/v0.10.1/Roundify_0.10.1.rmskin"
ChangelogLink3="https://github.com/NoahBRostant/Roundify/releases/download/v0.11.0/Roundify_0.11.0.rmskin"
ChangelogLink4="https://github.com/NoahBRostant/Roundify/releases/download/v0.11.1/Roundify_0.11.1.rmskin"
ChangelogLink5="https://github.com/NoahBRostant/Roundify/releases/download/v0.11.2/Roundify_0.11.2.rmskin"
ChangelogLink6="https://github.com/NoahBRostant/Roundify/releases/download/v0.12.0/Roundify_0.12.0.rmskin"
ChangelogLink7="https://github.com/NoahBRostant/Roundify/releases/download/v0.13.0/Roundify_0.13.0.rmskin"
ChangelogLink8=""

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
