------------------------------------------------------------------------------------ Variables ----------------------------------------------------------------------------------

[Variables]
DisplayVersion=1.0.0-beta.4

;Window Variables
Color1=39,39,39
Color2=47,47,47
Color3=75,75,75
Color4=57,57,57
Color5=52,52,52
Color6=EBCB8B
Color7=255,255,255
Color8=76,179,235
Color8A=63,149,196
Color9=191,97,106
WindowRadius=6
BorderWidth=1
BorderColor=75,75,75
TitleHeight=150
LPadding=350
Spacing=50
InputX=650
WindowWidth=886
WindowHeight=514
SidebarWidth=190
UpdaterWindowWidth=734
UpdaterWindowHeight=380
UpdaterSidebarWidth=244
ChangelogSlideHeight=272
ChangelogWidth=422

Option1Height=50
Option2Height=50


Padding1=200
Padding2=150
Padding3=100
Padding4=50

;Measures
CornerRadius=10
CornerColor=4,9,20
DisplayColor=4,9,20
SettingsOn=0
FullScreenOn=2
UpdateWinY=260
UpdateWinX=569

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
