------------------------------------------------------------------------------------ Variables ----------------------------------------------------------------------------------

[Variables]
DisplayVersion=1.0.0-beta.3

;Window Variables
Color1=39,39,39
Color2=47,47,47
Color3=75,75,75
Color4=57,57,57
Color5=52,52,52
Color6=EBCB8B       ;Yellow
Color7=216,222,233  ;White Text
Color8=76,194,255   ;Selected Blue
Color9=191,97,106
WindowRadius=6
BorderWidth=1
BorderColor=75,75,75
TitleHeight=150
LPadding=350
Spacing=50
InputX=650
Radius=(#TitleHeight#)
PaddingAmount=(#Radius#+#Spacing#)
Color=(#PaddingAmount#+#Spacing#)
Fullscreen=(#TitleHeight#)
SettingsButton=(#Fullscreen#+#Spacing#)
Line6=(#SettingsButton#+#Spacing#)

;Measures
CornerRadius=10
CornerColor=4,9,20
DisplayColor=4,9,20
SettingsOn=1
FullScreenOn=1
UpdateWinY=260
UpdateWinX=569

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
