------------------------------------------------------------------------------------ Variables ----------------------------------------------------------------------------------

[Variables]

;Window Variables
Color1=39,39,39
Color2=216,222,233
Color3=191,97,106
Color4=57,57,57
Color5=90,90,90
Color6=163,190,140
WindowRadius=10
TitleHeight=80
LPadding=15
Spacing=50
InputX=320
Line1=(#TitleHeight#)
Line2=(#Line1#+#Spacing#)
Line3=(#Line2#+#Spacing#)
Line4=(#Line3#+#Spacing#)
Line5=(#Line4#+#Spacing#)
Line6=(#Line5#+#Spacing#)

;Measures
CornerRadius=10
CornerColor=4,9,20
DisplayColor=4,9,20
SettingsOn=1
FullScreenOn=1

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
