------------------------------------------------------------------------------------ Variables ----------------------------------------------------------------------------------

[Variables]
DisplayVersion=1.0.0

;Window Variables
Color1=39,39,39
Color2=47,47,47
Color3=75,75,75
Color4=57,57,57
Color5=52,52,52
Color6=             ;Resurved
Color7=216,222,233  ;White Text
Color8=76,194,255   ;Selected Blue
Color9=191,97,106
WindowRadius=6
BorderWidth=2
BorderColor=75,75,75
TitleHeight=80
LPadding=15
Spacing=50
InputX=320
Line1=(#TitleHeight#)
Line2=(#Line1#+#Spacing#)
Line3=(#Line2#+#Spacing#)
Line4=(#Line3#+#Spacing#)
Line5=(#Line4#+#Spacing#)
Line6=(#Line5#+#Spacing#)
UpdateWinX=554
UpdateWinY=260
UpdaterOpen=1

;Measures
CornerRadius=10
CornerColor=4,9,20
DisplayColor=4,9,20
SettingsOn=1
FullScreenOn=1

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
